### ISSUE TITLE
[Logistic] Sprint 2 goals planning

### ISSUE THREAD

**Issue by yo1995** [DukeMobileDevCenter/Jigsaw#10]
In this sprint, a few expectations should be met

1. A prototype app get implemented with all the fundamental features

  - [x] welcome page #12 
  - [x] political "slider" #12
  - [x] player matching algorithm for 2 and 4 players #16 and #21 
  - [x] content presenting with `WKWebView` #19 
  - [x] real time chatting based on `Firebase` #11 
  - [x] questionnaire #5 
  - [x] result collecting #18 
  - [x] (optional) profile page #18 , not created since it is trivial < 3hrs.

2. Server side matching algorithm
3. Beta testing workflow
4. Documentation for implemented features
  - [x] use Wiki page: https://github.com/DukeMobileDevCenter/Jigsaw/wiki

**Comment by yo1995** [comment]
@profRic Today I wrapped up #21 and it should call for Sprint 2. 🎉  Pretty hard to gather all the pieces and make the app running! 😪 

Maybe we can set up another meeting to share the demo with clients next week, while I'll make small fixes this Sunday.
