### ISSUE TITLE
[Logistic] Release checklist

### ISSUE THREAD

**Issue by yo1995** [DukeMobileDevCenter/Jigsaw#108]
- [x] merge to master #118 
- [ ] create new app scheme on Firebase
- [ ] set url scheme in the app
- [ ] move the firebase billing account to Ric
- [ ] change bundle id. and create a new app on App Connect
- [x] screenshots, preview
- [x] app description, legal notes, app website
- [x] test account info
