### ISSUE TITLE
[Logistic] Sprint 4 goals planning

### ISSUE THREAD

**Issue by yo1995** [DukeMobileDevCenter/Jigsaw#57]
Refer to #10 

1. Fulfill clients suggestions on the improvements

- [x] Remove the onboarding display name step, and generate a jigsaw name instead #58
- [x] Capture screenshots for each screen for demo purpose
- [x] Onboarding political-neutral textual content
- [x] Topics instead of individual games, for each topic there is a step by step challenge (escape rooms) #67
- [x] Game how-to-play instructions
- [x] Return to the chatroom step when not everybody pass in 2 times #7
- [ ] ❌ Game score system, ranking, achievement - will move to Sprint 5 and later
- [x] "Take me to the game" randomly assign a player to a queue for a game #59 
- [x] ❓  Show how many answers they didn't get quite right, and returns to the chatroom step before
- [x] Drop game handling #66 - Tell all other players that some player dropped the game and the Jigsaw is broken. 😢 

2. Figure out how to distribute the app

@profRic Currently I cannot sign up for a personal Apple Developer account, which means I cannot upload the app to TestFlight or publish on AppStore. We need to work out a way to distribute the apps to testers and eventually upload to AppStore.

3. Localization preparation

Replace existing strings with localized string for future adaption.

**Comment by yo1995** [comment]
Currently I don't show how many question a player fails. It can add some difficulty to the game.

**Comment by yo1995** [comment]
https://www.moralmachine.net/

**Comment by yo1995** [comment]
Despite a few stuff not done, this Sprint is successfully wrapped up!
