### ISSUE TITLE
[Logistic] Sprint 5 goals planning

### ISSUE THREAD

**Issue by yo1995** [DukeMobileDevCenter/Jigsaw#73]
Before I finish, there are still a few things that should be done for the app. 

- [x] Build with Xcode 12, #76 
- [x] Account and anonym management, #45 
- [x] Replace some inappropriate images, #81 
- [x] Redesign some content, #80 and #79 
- [x] Show game score, #82 
- [x] Achievements and leaderboard, #84 
- [ ] Set up for testing

Also in the remaining time, try to embed in Game Center and add at least one score system.

**Comment by yo1995** [comment]
Address what I learned from Monday meeting and prioritize key tasks.

Also fix the bugs.

**Comment by yo1995** [comment]
Mostly done and move the remaining to sprint 6.
