### ISSUE TITLE
[Logistic] Sprint 6 goals planning

### ISSUE THREAD

**Issue by yo1995** [DukeMobileDevCenter/Jigsaw#93]
- [x] Achievements and leaderboard, #84
- [x] Randomizer changes, #83 
- [x] Redesign room levels, #80
- [x] Configure database rules, #41

**Comment by yo1995** [comment]
Done!
